### ISSUE TITLE
Support list-of-pairs interface from Underscore

### ISSUE THREAD

**Issue by eush77** [landau/zipmap#2]
[_.object](http://underscorejs.org/#object) is particularly useful in the way that it is easy to apply its single-argument form to other methods' return values.

``` js
var obj = _.object('one - 1, two - 2, three - 3'
                   .split(', ')
                   .map(function (s) { return s.split(' - '); }));
```

Can it be part of this module as well?

**Comment by landau** [comment]
I'm not sure I understand what you're looking to do with zipmap. Can you show me an example?

**Comment by eush77** [comment]
I am looking to generate objects with `zipmap`.

Suppose I have an array of key-value pairs in the form of `{key: 'key', value: 'value'}` and I want to make a single object out of this array.

``` js
> items
[ { key: 'foo', value: 'bar' },
  { key: 'baz', value: 'quux' } ]
```

In its current state `zipmap` accepts two arguments (`keys` and `vals`), which suggests that I make these arrays first and then join them with `zipmap`:

``` js
> var keys = items.map(function (item) { return item.key; });
> var vals = items.map(function (item) { return item.value; });
> zipmap(keys, vals)
{ foo: 'bar', baz: 'quux' }
```

This is not very convenient, and I have to come up with some arbitrary names along the way. The reason is that other functions always return a single element and I can't simply “pipe” this output to `zipmap`.

On the other hand, you can add the one-argument form, which could make it far more convenient to generate objects on the fly. For example:

``` js
> zipmap(items.map(function (item) {
    return [item.key, item.value];
  }))
{ foo: 'bar', baz: 'quux' }
```

**Comment by landau** [comment]
These seem like good ideas.

Here is what I'll do.
- Allow zipmap to accept a single arg
- If that arg is an array of objects those objects must conform to `key` and `value`
- if that arg is an array of arrays then split `key/value` automatically

**Comment by landau** [comment]
Done. Let me know what you think. Thanks!

**Comment by eush77** [comment]
Yay! This looks great.

One minor issue: `zipmap([])` throws a TypeError, which is probably not the desired behavior (I would say returning an empty object is).

``` js
> zipmap([{ key: 'foo', value: 'bar' }].filter(function (item) {
    return item.key == 'foo';
  }))
{ foo: 'bar' }
> zipmap([{ key: 'foo', value: 'bar' }].filter(function (item) {
    return item.key == 'fo';
  }))
TypeError: Expected vals to be an array
```
